### PR TITLE
Fix spin and precession periods

### LINKED ISSUE #12: Wrong spin period?
The spin period for PICO simulation is set to be 60 s, but I believe that TOAST expects this number in minutes (see [toast_satellite_sim.py](https://github.com/hpc4cmb/toast/blob/master/pipelines/toast_satellite_sim.py#L145)). If this is the case, the following lines of code are wrong:

- https://github.com/zonca/pico-simulations/blob/master/calibration_sim/pico_scanning.par#L4
- https://github.com/zonca/pico-simulations/blob/master/calibration_sim/pico_scanning.par#L8

### PR DESCRIPTION
**Pull request by zonca**
closes #12

### CODE REVIEW

**Comment by zonca** [comment]
@ziotom78 can you please cross-check this?

**Comment by ziotom78** [comment]
Ok, the periods now look ok.

I don't remember where did we take the angles for the spin axis and the precession angle, they differ slightly from the ones listed here: https://zzz.physics.umn.edu/ipsig/optimizingscanstrategy/start (30° and 65°). But i clearly remember I checked them.

**Comment by zonca** [comment]
@ziotom78 I have no idea, in https://github.com/zonca/pico-simulations/tree/fix-scan-periods/calibration_sim we mention we used https://zzz.physics.umn.edu/ipsig/baseline, but that also has 30 and 65 and looking at wiki history I don't see it changed ever. I added this fix, at this point we should re-check everything.

**Comment by ziotom78** [comment]
Ok, I rechecked everything, I took the advantage of this review to update the dipole parameters to Planck 2015, and to slightly reduce the sampling rate. It is still 10 times smaller than the nominal, but this helps in keeping the files small without compromising the results too much.

From my point of view, this PR can now be merged.

**Comment by zonca** [comment]
good thanks!

**Pull request merged**
